### ISSUE TITLE
Check the status of favourites

### ISSUE THREAD

**Issue by pandusonu2** [NITDgpOS/manga#27]
Add option to display the status of favourite titles. 

It can display in the form of
\<title\> \<latest chapter release\> \<date of release\>

**Comment by DarkSouL11** [comment]
@pandusonu2 should this option be added to fav.sh?

**Comment by pandusonu2** [comment]
@DarkSouL11 No, it should be added to newsteller.sh
`bash newsteller.sh -f` should return status of favourites.
