### ISSUE TITLE
Fails when chap has more than 100 pages

### ISSUE THREAD

**Issue by abh3po** [NITDgpOS/manga#3]
Basically due to the line : https://github.com/pandusonu2/manga/blob/master/downloader.sh#L26

**Comment by abh3po** [comment]
are you sure this is a newcomer issue? i mean implementation has to be clear for a newcomer and i dont see a way to change this back

**Comment by pandusonu2** [comment]
Make the following for loop to an infinite loop https://github.com/NIT-dgp/manga/blob/master/downloader.sh#L28

**Comment by pandusonu2** [comment]
Another fix has been proposed before by @shiningsurya https://github.com/shiningsurya/manga/commit/35b776699a89ccf2cf3d432032870c825aa2cad8 But I would prefer to keep an infinite loop.

**Comment by abh3po** [comment]
maybe @shiningsurya can make that change better as well? also in newcomer issues the task is spelled out you type down the exact change that needs to be done, think of it as a way of you teaching them the git/github workflow, i would suggest making this a difficulty/low issue
