### ISSUE TITLE
Use a function for repeated piece of code

### ISSUE THREAD

**Issue by pandusonu2** [NITDgpOS/manga#30]
<pre>
$(echo $link | grep -aob '"' | grep -oE '[0-9]+' | sed "<val>q;d")
</pre>
is used multiple times. Write a function which takes in argument of $link and <val> and returns desired output.

**Comment by hasan356** [comment]
can you explain what does this line doing

**Comment by pandusonu2** [comment]
That line is getting the index of the ith occurrence of "
The value of i will be given in ```seq <i>q; d```
