### ISSUE TITLE
Check before adding favourites

### ISSUE THREAD

**Issue by pandusonu2** [NITDgpOS/manga#31]
When you execute 'bash fav.sh', we add fav titles to a hidden .fav file. But we don't check if the title is valid.
So make changes to fav.sh to check if the title is valid or not before adding it .fav

**Comment by DarkSouL11** [comment]
What do you mean by a valid title?
I can think of two possibilities:
1) If there is a manga already downloaded with that title, then that would be valid else not valid.
2) If there is a manga with that title available in the mangareader site, then that would be valid else not valid. 
Sorry if this is silly doubt :stuck_out_tongue:

**Comment by pandusonu2** [comment]
The second one :P 
Suppose I say I want to add "pandusonu2" to the titles, would be non-sensical right?!
As for your 1, favourites has nothing to do with downloaded/not downloaded. Favourites will be used later by newsteller :)
