### ISSUE TITLE
Needs GUI 

### ISSUE THREAD

**Issue by pandusonu2** [NITDgpOS/manga#4]
The current downloader works totally from the command line. Would be neat to have an interface.
Need mock-ups and software which can be used.

**Comment by ghoshbishakh** [comment]
The code is in bash. But with growing complexity of features and GUI will it remain manageable in bash?

**Comment by abh3po** [comment]
/me has same issue, why not keep it simple as CLI ? something on the lines of `youtube-dl`

**Comment by pandusonu2** [comment]
Ah, I would keep it to minimum, and it would be launced via bash script only :) 
A gui would be better to keep track of the chapter list one has downloaded. Without which, one should browse the folders. If we have multiple titles, too many folders to browse through, a GUI breaks it all

**Comment by abh3po** [comment]
@pandusonu2 dont you think manga-gui should be a seperate repo? not sure

**Comment by pandusonu2** [comment]
No, it would just be a display with drop down menu for titles and respective chapters. Would be too little for another separate repo.

**Comment by pandusonu2** [comment]
Right now, all the work is done via the command line. I would like to build a GUI easier work, since I've merged Python now, it can be constructed in it. 
My plan:
Window
-right side menu bar showing tree structure 
-left side document view for viewing pdf.
The current GUI requirement is just to show the already downloaded manga chapters.

**Comment by pandusonu2** [comment]
The hierarchical structure of it will be:
Window
-TreeView (On the left side)
-Document View (On the right side)
In the menu bar, under file option, there will be an option to download manga. On clicking, a box pops up with three fields namely "name" "start" and "end" which will later be used to call downloader.sh using -t and -c tags

**Comment by pandusonu2** [comment]
Ta da :P Expected GUI
![chap51](https://cloud.githubusercontent.com/assets/14852954/22395247/8352c78c-e55d-11e6-8e66-7e8203ac877e.png)

**Comment by abh3po** [comment]
/me thinks he'kk start to read anga after this feature :P

**Comment by pandusonu2** [comment]
GSoC Heat work done on this issue, just needs a widget to display the pdf. Awesome work by CompoPrasad :D 
![gsocheatt](https://cloud.githubusercontent.com/assets/14852954/22419943/cd9d2dce-e705-11e6-8c36-bd14bd936591.png)

**Comment by XTremeRox** [comment]
We can do this guys,
Port the whole thing to python and use the subprocess module for "BASH" lines ? The expected GUI is wonderful though :)

**Comment by pandusonu2** [comment]
@Compro-Prasad Awesome work on this (/.\) I dont think we figured out a pdf displayer yet. But closing this issue, as the main part of GUI is already in the repository


Closing comments: Work done by @Compro-Prasad the final result is in the comments

**Comment by Compro-Prasad** [comment]
I could look for a package/library if I have time.

**Comment by pandusonu2** [comment]
Open a new Issue for that
