### ISSUE TITLE
Use firefox instead of google chrome for pages.sh

### ISSUE THREAD

**Issue by abh3po** [NITDgpOS/manga#9]
firefox is available on all os' while chrome may not be there, plus firefox has the same alias on all os' and while chrome is different on rpm and deb

**Comment by pandusonu2** [comment]
Adding an option while executing would be more preferred :D

**Comment by pandusonu2** [comment]
Just make changes to https://github.com/NIT-dgp/manga/blob/master/page.sh#L2
